---
title: "class10"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


## 
<h1> 政治学数据分析与编程 </h1>
<h2> 第十讲 </h2>

吕杰

中国人民大学国际关系学院政治学系

<script language=JavaScript>
today=new Date();
function initArray(){
this.length=initArray.arguments.length
for(var i=0;i<this.length;i++)
this[i+1]=initArray.arguments[i] }
var d=new initArray(
"星期日",
"星期一",
"星期二",
"星期三",
"星期四",
"星期五",
"星期六");
document.write(
"<font color=#333 style='font-size:9pt;font-family: 楷体'> ",
today.getFullYear(),"年",
today.getMonth()+1,"月",
today.getDate(),"日",
d[today.getDay()+1],
"</font>" );
</script>

## 内容提纲

+ 从观测数据向实验数据逼近
+ 多层线性模型
+ 贝叶斯统计模型
+ 文本数据分析

## 观测数据分析存在的问题

很难满足因果推断的要求

+ 虚假关系（Spurious relationships）
+ 遗漏变量（Omitted variables）
+ 内生性（Endogeneity）
+ 大量的假设（Assumptions）

## 如何向实验数据靠拢？

通过研究设计来尽量让观测数据逼近实验数据，关键就是如何找到外生的刺激/变量。

+ 自然实验（Natural experiments）
+ 断点回归（Regression discontinuity design）
+ 多重差分（Difference in differences）
+ 工具变量（Instrumental varialbe）

## 多层模型的不同理解 I
特殊的数据结构（Nested data structure， Multilevel Modeling）

+ 数据来自于不同的层级
+ 不同层级数据之间的嵌套
+ 违背了 IID
+ 经典的案例
  * 学校和教师绩效的考察（学生作为底层研究对象）
  * 企业文化对职员行为的影响（职员作为底层研究对象）
  * 环境对民众政治行为和态度的影响（民众作为底层研究对象）
  
## 多层模型的不同理解 II
模型参数的多层嵌套（Nested parameter structure, Hierarchical Modeling）

+ 整体模型： $y|x,\beta,\sigma \sim N(x\beta,\sigma^2)$
+ 参数模型 I： $\beta \sim Prior$
+ 参数模型 II： $\sigma \sim Prior$
+ Bayesian法则进行统计推断

## 多层模型的不同理解 III
统计效应的一致性（Random vs. Fixed effects, Mixed-Effect Modeling）

+ 固定效应（固定的截距、固定的回归系数）
+ 随机效应（变化的截距、变化的回归系数）
+ 环境效应（Contextual effects）
+ 相应的统计检测（e.g., Deviance tests）

## 贝叶斯学派和频率学派的异同
|贝叶斯学派（Bayesian）|频率学派（Frequentist）|
|:----:|:----:|
|假说和数据都有对应概率分布|假说没有对应的概率分布|
|依赖于观测到数据的先验概率和似然函数|依赖于观测到及未观测到数据的似然函数|
|需要建立相对主观的先验概率|不需要先验概率|
|需要相对高强度的计算|一般不需要太高强度的计算|
| | |

## 贝叶斯统计推断的一般步骤
贝叶斯统计推断对文献和数据给与同等的重视程度

+ 依据文献设定数据产生的过程模型
+ 依据文献设定参数模型
+ 依据文献设定参数的先验概率
+ 纳入数据计算参数的后验概率（MCMC）
+ 检验后验概率和MCMC的收敛性
+ 呈现参数的后验概率（credible intervals, high density intervals）进行统计推断

## 文本数据分析的逻辑
自然语言处理（Natural Language Processing, NLP）

+ 计算机科学、人工智能、语言学
+ 句法语义分析
+ 信息抽取
+ 文本挖掘
+ 机器翻译
+ 信息检索
+ 问答系统
+ 对话系统

## 文本分析的步骤
社会科学研究中的文本分析

+ 整理语言文本（language corpora）
+ 文本处理（stemming, tokenizing）
  * 去除无意义的辅助词
  * 不同的时态词汇的一致化
  * 分词
  * 语料库
  * 词典
+ 词频分析（比如词云图等）
+ 语义分析（比如对词汇积极和消极情绪的分析）
+ 主题抽取（比如 Topic modeling）




